### ISSUE TITLE
[Bug] Compilation error in test vector/insert_size

### ISSUE THREAD

**Issue by SuperDulli** [Mikastiv/ft_containers-terminator#1]
When trying to compile the test insert_size in vector, I get an compiler error stating that: "'numeric_limits' is not a member of 'std'".

Reproduce:
`bash run_test_files.sh vector insert_size`.

Possible solution:
include the header limits.

**Comment by mikastiv** [comment]
It is true that I didn't include the header limits for this test, but it was working fine for me on my linux machine and at my 42 school. I still added the header in my last commit

Did it fix the bug for you?

**Comment by SuperDulli** [comment]
I also tested in on the school Mac where it compiled without a problem. But now it works also on my private machine.

Thank you!
