### ISSUE TITLE
misleading map test

### ISSUE THREAD

**Issue by oouazize** [Mikastiv/ft_containers-terminator#2]
I think there is a misleading error when testing the upper_bound() and equal_range() methods the STL map segfaults when passing the INT_MAX as an argument to the methods and my container has the same behavior but the tester shows me KO I think this case shouldn't be tested or the result get compared with the STL one
```
        b = m.upper_bound(std::numeric_limits<int>::max());

        PRINT_BOUND(b, m.end());

        m.insert(NAMESPACE::make_pair(std::numeric_limits<int>::max(), "max"));

        b = m.upper_bound(std::numeric_limits<int>::max());

        PRINT_BOUND(b, m.end());
```

I suggest

```
        m.insert(NAMESPACE::make_pair(std::numeric_limits<int>::max(), "max"));

        b = m.upper_bound(std::numeric_limits<int>::max() - 1);

        PRINT_BOUND(b, m.end());
```

**Comment by mikastiv** [comment]
I don't see how this could cause a segfault. I tested with clang and gcc with both libc++ and libstd++. Which compiler version are you using and which standard library?

**Comment by oouazize** [comment]
c++ -Wall -Wextra -Werror -std=c++98
#include <iostream>

**Comment by oouazize** [comment]
Oh, I am sorry, the standard map is working fine, but I see it's giving me a random value every time I run the program, do you know why, and about const map, it will give me the value that it's before the largest one

**Comment by oouazize** [comment]
Hi again,  I discovered that he returned just end(), it's the same that i returned too, but the difference is that my end() doesn't have any first and second values

**Comment by oouazize** [comment]
why would you check the value stored in end() if you already know the function will return end() and end() is not dereferenceable so there will be an undefined behavior therefore the test will always show KO to someone with different compiler

the test could be something similar to this
```
        b = m.upper_bound(std::numeric_limits<int>::max());

        if (b == m.end()) std::cout << "OK" << std::endl;
```

**Comment by mikastiv** [comment]
I'm pretty sure I never check the value in end because it is undefined behaviour. That is why I pass the end iterator to the print macro. If it does try to print yours, it is probably because the equal comparison did not return true when I checked if it was end. If you found a place where I do print end, please show me the file and line. Otherwise, I'm going to close this issue.

**Comment by oouazize** [comment]
I am in a mess, you protected correctly I don't remember why it's given me a segfault and how I see it like that and now it's working with your macro, You did good work, sorry for inconveniencing you, please accept my apologies

**Comment by mikastiv** [comment]
No worries 🙂
